//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecommerceG3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_db
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product_db()
        {
            this.inventories = new HashSet<inventory>();
        }
    
        public string Product_name { get; set; }
        public int Product_ID { get; set; }
        public string Description { get; set; }
        public string Product_Cat { get; set; }
        public int Price { get; set; }
        public int qty { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inventory> inventories { get; set; }
    }
}
